In [1]:
import anndata as ad
import numpy as np
import pandas as pd

In [ ]:
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator
from rdkit.DataStructs import ConvertToNumpyArray

In [2]:
import pubchempy as pcp
from tqdm import tqdm

In [3]:
df_dili = pd.read_pickle('../../dili.pkl')

In [4]:
df_dili = df_dili.drop(columns=['cmap_name', 'symbol', 'code', 'symbol_', 'LPM_emb'])

In [5]:
df_dili['pubchem_cid_key'] = df_dili['pubchem_cid'].copy().astype(object)

In [6]:
df_dili.loc[~df_dili['pubchem_cid_key'].isna(), 'pubchem_cid_key'] = df_dili.loc[~df_dili['pubchem_cid_key'].isna(), 'pubchem_cid_key'].astype(int).astype(str)

In [7]:
print(1)

1

In [8]:
import os
os.makedirs('./dili_single_run_all_l1000_25_50_epochs/', exist_ok=True)
epoch_dirs = os.listdir('../../../lpm_style/files/single_run_all_50_epochs/')
epoch_dirs.remove('last')

for epoch_dir in epoch_dirs:
    df_pert_all = pd.read_pickle(f'../../../lpm_style/files/single_run_all_50_epochs/{epoch_dir}/df_pert.pkl')\
                    .rename(columns={'symbol': 'symbol_all', 
                                     'code': 'code_all', 
                                     'lpm_style_embeddings': 
                                     'lpm_style_embeddings_all'})

    df_pert_l1000 = pd.read_pickle(f'../../../lpm_style/files/single_run_l1000_50_epochs/{epoch_dir}/df_pert.pkl')\
                    .rename(columns={'symbol': 'symbol_l1000', 
                                     'code': 'code_l1000', 
                                     'lpm_style_embeddings': 
                                     'lpm_style_embeddings_l1000'})

    
    df_dili_merged = df_dili.merge(df_pert_all, left_on='pubchem_cid_key', right_on='symbol_all', how='left')\
                            .merge(df_pert_l1000, left_on='pubchem_cid_key', right_on='symbol_l1000', how='left')\
                            .drop(columns=['pubchem_cid_key'])
    
    
    tag = int(epoch_dir.split('_')[-1])
    df_dili_merged.to_pickle(f"./dili_single_run_all_l1000_25_50_epochs/dili_lpm_style_embeddings_epoch_{tag + 1}.pkl")

In [18]:
! pwd

/ictstr01/home/icb/olga.novitskaia/op3_signatures/notebooks/create_embeddings_for_datasets_lpm_style_many_epochs

In [10]:
pd.read_pickle(f'./dili_single_run_all_l1000_25_epochs/dili_lpm_style_embeddings_epoch_1.pkl').head()

,pert_id,LTKBID,compound_name,DILIrank,label_section,severity_class,DILIst,roa,source,livertox_score,...,livertox_mechanism_summary,pubchem_cid,retrieved_smiles,ECFP:2,symbol_all,code_all,lpm_style_embeddings_all,symbol_l1000,code_l1000,lpm_style_embeddings_l1000
0,4-aminosalicylic acid,LT00505,4-aminosalicylic acid,Most-DILI-Concern,Warnings and precautions,5.0,NaN,Oral,DILIrank,NaN,...,NaN,4649.0,C1=CC(=C(C=C1N)O)C(=O)O,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",4649,15925.0,"[0.16551190614700317, 0.2558914124965668, -0.3...",4649,6288.0,"[-1.0120770931243896, -0.7670892477035522, -0...."
1,4-phenylbutyric acid,LT02343,4-phenylbutyric acid,Ambiguous DILI-concern,Adverse reactions,4.0,NaN,NaN,DILIrank,NaN,...,NaN,4775.0,C1=CC=C(C=C1)CCCC(=O)O,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",4775,16305.0,"[-0.02869339846074581, -0.029099829494953156, ...",4775,6503.0,"[0.7403006553649902, -0.5896013379096985, -0.3..."
2,Abacavir,LT00040,Abacavir,Most-DILI-Concern,Warnings and precautions,8.0,NaN,Oral,DILIrank,C,...,"Hepatitis, Cholestasis/Biliary, Hypersensitivi...",441300.0,C1CC1NC2=C3C(=NC(=N2)N)N(C=N3)C4CC(C=C4)CO,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",441300,12052.0,"[0.2815607190132141, 0.18812452256679535, -0.1...",NaN,NaN,NaN
3,Abatacept,LT01402,Abatacept,Less-DILI-Concern,No match,0.0,NaN,Intravenous,DILIrank,C,...,"Hepatitis, Necrosis, Hypersensitivity, idiosyn...",NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN
4,Abciximab,LT01330,Abciximab,No-DILI-Concern,No match,0.0,NaN,Intravenous,DILIrank,NaN,...,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
pd.read_pickle(f'./dili_single_run_all_l1000_25_50_epochs/dili_lpm_style_embeddings_epoch_26.pkl').head()

,pert_id,LTKBID,compound_name,DILIrank,label_section,severity_class,DILIst,roa,source,livertox_score,...,livertox_mechanism_summary,pubchem_cid,retrieved_smiles,ECFP:2,symbol_all,code_all,lpm_style_embeddings_all,symbol_l1000,code_l1000,lpm_style_embeddings_l1000
0,4-aminosalicylic acid,LT00505,4-aminosalicylic acid,Most-DILI-Concern,Warnings and precautions,5.0,NaN,Oral,DILIrank,NaN,...,NaN,4649.0,C1=CC(=C(C=C1N)O)C(=O)O,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",4649,15925.0,"[0.06020880490541458, 0.1725081503391266, 0.16...",4649,6288.0,"[0.0152207650244236, 0.23670713603496552, 0.01..."
1,4-phenylbutyric acid,LT02343,4-phenylbutyric acid,Ambiguous DILI-concern,Adverse reactions,4.0,NaN,NaN,DILIrank,NaN,...,NaN,4775.0,C1=CC=C(C=C1)CCCC(=O)O,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",4775,16305.0,"[-0.012761224992573261, -0.07184681296348572, ...",4775,6503.0,"[0.04819692298769951, 0.09728066623210907, 0.1..."
2,Abacavir,LT00040,Abacavir,Most-DILI-Concern,Warnings and precautions,8.0,NaN,Oral,DILIrank,C,...,"Hepatitis, Cholestasis/Biliary, Hypersensitivi...",441300.0,C1CC1NC2=C3C(=NC(=N2)N)N(C=N3)C4CC(C=C4)CO,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",441300,12052.0,"[0.04464007541537285, 0.0872591882944107, -0.0...",NaN,NaN,NaN
3,Abatacept,LT01402,Abatacept,Less-DILI-Concern,No match,0.0,NaN,Intravenous,DILIrank,C,...,"Hepatitis, Necrosis, Hypersensitivity, idiosyn...",NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN
4,Abciximab,LT01330,Abciximab,No-DILI-Concern,No match,0.0,NaN,Intravenous,DILIrank,NaN,...,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN