In [1]:
import anndata as ad
import os
import pandas as pd

## Download results

In [2]:
def dict_to_pd(d):
    rows = []

    for outer_key, inner in d.items():
        row = {
            "dataset_id": inner["dataset_id"],
            "method_id": inner["method_id"],
        }
        
        # Use values from "d" as column names
        for col_name, value in zip(inner["metric_ids"], inner["metric_values"]):
            row[col_name] = value
            
        rows.append(row)
    
    df = pd.DataFrame(rows, index=d.keys())
    return df

In [3]:
control_path = '../../data/benchmark/results/metrics/control_methods/'
methods_path = '../../data/benchmark/results/metrics/methods/'

In [4]:
file_name_err = 'mean_rowwise_error.h5ad'
file_name_corr = 'mean_rowwise_correlation.h5ad'

In [5]:
methods_err = {}
methods_corr = {}
for item in os.listdir(methods_path):
    err = ad.read_h5ad(f'{methods_path}{item}/{file_name_err}').uns
    corr = ad.read_h5ad(f'{methods_path}{item}/{file_name_corr}').uns
    methods_err[item] = err
    methods_corr[item] = corr

In [6]:
control_err = {}
control_corr = {}
for item in os.listdir(control_path):
    err = ad.read_h5ad(f'{control_path}{item}/{file_name_err}').uns
    corr = ad.read_h5ad(f'{control_path}{item}/{file_name_corr}').uns
    control_err[item] = err
    control_corr[item] = corr

In [7]:
df_method_err = dict_to_pd(methods_err)
df_control_err = dict_to_pd(control_err)

In [8]:
df_method_corr = dict_to_pd(methods_corr)
df_control_corr = dict_to_pd(control_corr)

## Mean rowwise error

### Methods

In [12]:
df_method_err[df_method_err.index.str.contains('subsample')].sort_values(by="mean_rowwise_rmse")

,dataset_id,method_id,mean_rowwise_rmse,mean_rowwise_mae
nn_retraining_with_pseudolabels_subsample_fp_concat_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels_subsample,0.774643,0.560257
nn_retraining_with_pseudolabels_subsample_lpm_trainable_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels_subsample_lpm_...,0.775017,0.561174
nn_retraining_with_pseudolabels_subsample_fp_concat_dense,neurips-2023-data,nn_retraining_with_pseudolabels_subsample,0.775617,0.564674
nn_retraining_with_pseudolabels_subsample_lpm_concat_dense,neurips-2023-data,nn_retraining_with_pseudolabels_subsample,0.775986,0.560758
nn_retraining_with_pseudolabels_subsample_fp_fixed_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels_subsample_fp_f...,0.776122,0.565059
nn_retraining_with_pseudolabels_subsample_fp_trainable_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels_subsample_fp_t...,0.777387,0.565474
nn_retraining_with_pseudolabels_subsample_lpm_concat_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels_subsample,0.778754,0.558843
nn_retraining_with_pseudolabels_subsample_none,neurips-2023-data,nn_retraining_with_pseudolabels_subsample_none,0.780259,0.557460
nn_retraining_with_pseudolabels_subsample_lpm_fixed_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels_subsample_lpm_...,0.784827,0.563128

### Control methods

In [10]:
df_control_err.sort_values(by="mean_rowwise_rmse")

,dataset_id,method_id,mean_rowwise_rmse,mean_rowwise_mae
ground_truth,neurips-2023-data,ground_truth,0.000000,0.000000
mean_across_celltypes,neurips-2023-data,mean_across_celltypes,0.892474,0.643716
mean_outcome,neurips-2023-data,mean_outcome,0.899233,0.635633
zeros,neurips-2023-data,zeros,0.917925,0.635087
mean_across_compounds,neurips-2023-data,mean_across_compounds,0.942813,0.697865
sample,neurips-2023-data,sample,1.363488,0.963245

## Mean rowwise correlation

### Methods

In [15]:
df_method_corr[df_method_corr.index.str.contains('subsample')].sort_values(by="mean_rowwise_pearson", ascending=False)
#df_method_corr.sort_values(by="mean_rowwise_spearman", ascending=False)

,dataset_id,method_id,mean_rowwise_pearson,mean_rowwise_spearman,mean_rowwise_cosine
nn_retraining_with_pseudolabels_subsample_fp_trainable_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels_subsample_fp_t...,0.493828,0.463721,0.496775
nn_retraining_with_pseudolabels_subsample_lpm_trainable_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels_subsample_lpm_...,0.493755,0.464018,0.496773
nn_retraining_with_pseudolabels_subsample_none,neurips-2023-data,nn_retraining_with_pseudolabels_subsample_none,0.489317,0.461187,0.492613
nn_retraining_with_pseudolabels_subsample_lpm_concat_dense,neurips-2023-data,nn_retraining_with_pseudolabels_subsample,0.488421,0.459614,0.491452
nn_retraining_with_pseudolabels_subsample_fp_fixed_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels_subsample_fp_f...,0.486703,0.457860,0.489845
nn_retraining_with_pseudolabels_subsample_lpm_concat_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels_subsample,0.486512,0.458764,0.489716
nn_retraining_with_pseudolabels_subsample_fp_concat_dense,neurips-2023-data,nn_retraining_with_pseudolabels_subsample,0.485278,0.456173,0.488346
nn_retraining_with_pseudolabels_subsample_lpm_fixed_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels_subsample_lpm_...,0.480957,0.453460,0.484156
nn_retraining_with_pseudolabels_subsample_fp_concat_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels_subsample,0.479586,0.451508,0.482795

### Control methods

In [12]:
df_control_corr.sort_values(by="mean_rowwise_spearman", ascending=False)

,dataset_id,method_id,mean_rowwise_pearson,mean_rowwise_spearman,mean_rowwise_cosine
ground_truth,neurips-2023-data,ground_truth,NaN,1.000000,NaN
mean_across_celltypes,neurips-2023-data,mean_across_celltypes,0.297152,0.280571,0.301747
mean_across_compounds,neurips-2023-data,mean_across_compounds,0.259385,0.242509,0.262827
mean_outcome,neurips-2023-data,mean_outcome,0.219819,0.211683,0.226435
sample,neurips-2023-data,sample,0.050696,0.054819,0.053091
zeros,neurips-2023-data,zeros,0.000000,0.000000,0.000000