In [1]:
import anndata as ad
import os
import pandas as pd

## Download results

In [2]:
def dict_to_pd(d):
    rows = []

    for outer_key, inner in d.items():
        row = {
            "dataset_id": inner["dataset_id"],
            "method_id": inner["method_id"],
        }
        
        # Use values from "d" as column names
        for col_name, value in zip(inner["metric_ids"], inner["metric_values"]):
            row[col_name] = value
            
        rows.append(row)
    
    df = pd.DataFrame(rows, index=d.keys())
    return df

In [3]:
control_path = '../data/benchmark/results/metrics/control_methods/'
methods_path = '../data/benchmark/results/metrics/methods/'

In [4]:
file_name_err = 'mean_rowwise_error.h5ad'
file_name_corr = 'mean_rowwise_correlation.h5ad'

In [5]:
methods_err = {}
methods_corr = {}
for item in os.listdir(methods_path):
    err = ad.read_h5ad(f'{methods_path}{item}/{file_name_err}').uns
    corr = ad.read_h5ad(f'{methods_path}{item}/{file_name_corr}').uns
    methods_err[item] = err
    methods_corr[item] = corr

In [6]:
control_err = {}
control_corr = {}
for item in os.listdir(control_path):
    err = ad.read_h5ad(f'{control_path}{item}/{file_name_err}').uns
    corr = ad.read_h5ad(f'{control_path}{item}/{file_name_corr}').uns
    control_err[item] = err
    control_corr[item] = corr

In [7]:
df_method_err = dict_to_pd(methods_err)
df_control_err = dict_to_pd(control_err)

In [8]:
df_method_corr = dict_to_pd(methods_corr)
df_control_corr = dict_to_pd(control_corr)

## Mean rowwise error

### Methods

In [9]:
df_method_err.sort_values(by="mean_rowwise_rmse")

,dataset_id,method_id,mean_rowwise_rmse,mean_rowwise_mae
nn_retraining_with_pseudolabels,neurips-2023-data,nn_retraining_with_pseudolabels,0.755927,0.546358
nn_retraining_with_pseudolabels_embeddings_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels,0.759375,0.547891
nn_retraining_with_pseudolabels_fingerprints_fp_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels,0.759427,0.550008
nn_retraining_with_pseudolabels_embeddings_dense,neurips-2023-data,nn_retraining_with_pseudolabels,0.760094,0.551483
nn_retraining_with_pseudolabels_fingerprints_fp_dense,neurips-2023-data,nn_retraining_with_pseudolabels,0.761362,0.554724
scape,neurips-2023-data,scape,0.774636,0.571945
lgc_ensemble_direct,neurips-2023-data,lgc_ensemble,0.795568,0.578494
pyboost,neurips-2023-data,pyboost,0.795777,0.560939
jn_ap_op2,neurips-2023-data,jn_ap_op2,0.896406,0.652236
transformer_ensemble,neurips-2023-data,transformer_ensemble,0.899493,0.634239

### Control methods

In [10]:
df_control_err.sort_values(by="mean_rowwise_rmse")

,dataset_id,method_id,mean_rowwise_rmse,mean_rowwise_mae
ground_truth,neurips-2023-data,ground_truth,0.000000,0.000000
mean_across_celltypes,neurips-2023-data,mean_across_celltypes,0.892474,0.643716
mean_outcome,neurips-2023-data,mean_outcome,0.899233,0.635633
zeros,neurips-2023-data,zeros,0.917925,0.635087
mean_across_compounds,neurips-2023-data,mean_across_compounds,0.942813,0.697865
sample,neurips-2023-data,sample,1.363488,0.963245

## Mean rowwise correlation

### Methods

In [11]:
df_method_corr.sort_values(by="mean_rowwise_spearman", ascending=False)

,dataset_id,method_id,mean_rowwise_pearson,mean_rowwise_spearman,mean_rowwise_cosine
nn_retraining_with_pseudolabels,neurips-2023-data,nn_retraining_with_pseudolabels,0.490362,0.462083,0.493576
nn_retraining_with_pseudolabels_embeddings_dense,neurips-2023-data,nn_retraining_with_pseudolabels,0.484197,0.456996,0.487342
nn_retraining_with_pseudolabels_embeddings_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels,0.484176,0.456850,0.487432
nn_retraining_with_pseudolabels_fingerprints_fp_dense,neurips-2023-data,nn_retraining_with_pseudolabels,0.482727,0.454459,0.485924
nn_retraining_with_pseudolabels_fingerprints_fp_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels,0.481321,0.453544,0.484589
scape,neurips-2023-data,scape,0.472742,0.441614,0.475776
pyboost,neurips-2023-data,pyboost,0.460455,0.438837,0.463593
lgc_ensemble_direct,neurips-2023-data,lgc_ensemble,0.450067,0.423551,0.453961
jn_ap_op2,neurips-2023-data,jn_ap_op2,0.326674,0.304523,0.329534
transformer_ensemble,neurips-2023-data,transformer_ensemble,0.218039,0.213368,0.223590

### Control methods

In [12]:
df_control_corr.sort_values(by="mean_rowwise_spearman", ascending=False)

,dataset_id,method_id,mean_rowwise_pearson,mean_rowwise_spearman,mean_rowwise_cosine
ground_truth,neurips-2023-data,ground_truth,NaN,1.000000,NaN
mean_across_celltypes,neurips-2023-data,mean_across_celltypes,0.297152,0.280571,0.301747
mean_across_compounds,neurips-2023-data,mean_across_compounds,0.259385,0.242509,0.262827
mean_outcome,neurips-2023-data,mean_outcome,0.219819,0.211683,0.226435
sample,neurips-2023-data,sample,0.050696,0.054819,0.053091
zeros,neurips-2023-data,zeros,0.000000,0.000000,0.000000