In [1]:
print(1)

1

In [2]:
import anndata as ad
import os
import pandas as pd

## Download results

In [3]:
def dict_to_pd(d):
    rows = []

    for outer_key, inner in d.items():
        row = {
            "dataset_id": inner["dataset_id"],
            "method_id": inner["method_id"],
        }
        
        # Use values from "d" as column names
        for col_name, value in zip(inner["metric_ids"], inner["metric_values"]):
            row[col_name] = value
            
        rows.append(row)
    
    df = pd.DataFrame(rows, index=d.keys())
    return df

In [4]:
control_path = '../../data/benchmark/results/metrics/control_methods/'
methods_path = '../../data/benchmark/results/metrics/methods/'

In [5]:
file_name_err = 'mean_rowwise_error.h5ad'
file_name_corr = 'mean_rowwise_correlation.h5ad'

In [6]:
methods_err = {}
methods_corr = {}
for item in os.listdir(methods_path):
    err = ad.read_h5ad(f'{methods_path}{item}/{file_name_err}').uns
    corr = ad.read_h5ad(f'{methods_path}{item}/{file_name_corr}').uns
    methods_err[item] = err
    methods_corr[item] = corr

In [7]:
control_err = {}
control_corr = {}
for item in os.listdir(control_path):
    err = ad.read_h5ad(f'{control_path}{item}/{file_name_err}').uns
    corr = ad.read_h5ad(f'{control_path}{item}/{file_name_corr}').uns
    control_err[item] = err
    control_corr[item] = corr

In [8]:
df_method_err = dict_to_pd(methods_err)
df_control_err = dict_to_pd(control_err)

In [9]:
df_method_corr = dict_to_pd(methods_corr)
df_control_corr = dict_to_pd(control_corr)

## Mean rowwise error

### Methods

* `nn_retraining_with_pseudolabels_mol_emb_subsample_lpm_concat_dense` - concatenation of fixed LPM embedding with 2 trainable specified in the initial architecture of the models: cell type and small molecule embeddings, before concatenation LPM embedding was projected with an additional Dense layer.
* `nn_retraining_with_pseudolabels_mol_emb_subsample_fp_concat_not_dense` - concatenation of fixed ECFP:2 embedding with 2 trainable: cell type and small molecule embeddings, before concatenation **no** additional Dense layer was applied.
* `nn_retraining_with_pseudolabels_mol_emb_subsample_fp_concat_dense` - concatenation of fixed ECFP:2 embedding with 2 trainable: cell type and small molecule embeddings, before concatenation ECFP:2 embedding was projected with an additional Dense layer.
* `nn_retraining_with_pseudolabels_mol_emb_subsample_lpm_trainable` - small molecule unfreezed embedding was initialized with LPM embedding information and then projected with a Dense layer to match original `emb_out` dimentions.
* `nn_retraining_with_pseudolabels_mol_emb_subsample_fp_fixed` - small molecule freezed embedding was initialized with ECFP:2 embedding information and then projected with a Dense layer to match original `emb_out` dimentions.
* `nn_retraining_with_pseudolabels_mol_emb_subsample_fp_trainable` - small molecule unfreezed embedding was initialized with ECFP:2 embedding information and then projected with a Dense layer to match original `emb_out` dimentions.
* `nn_retraining_with_pseudolabels_mol_emb_subsample_lpm_concat_not_dense` - concatenation of fixed LPM embedding with 2 trainable: cell type and small molecule embeddings, before concatenation **no** additional Dense layer was applied.
* `nn_retraining_with_pseudolabels_mol_emb_subsample_none` - Original architecture of models without additional embedding information.
* `nn_retraining_with_pseudolabels_mol_emb_subsample_lpm_fixed` - small molecule freezed embedding was initialized with LPM embedding information and then projected with a Dense layer to match original `emb_out` dimentions.

In [10]:
df_method_err[df_method_err.index.str.contains('_mol_emb_subsample')].sort_values(by="mean_rowwise_rmse")

,dataset_id,method_id,mean_rowwise_rmse,mean_rowwise_mae
nn_retraining_with_pseudolabels_mol_emb_subsample_lpm_concat_dense,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_lpm_co...,0.773798,0.559320
nn_retraining_with_pseudolabels_mol_emb_subsample_fp_concat_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_fp_con...,0.774243,0.559763
nn_retraining_with_pseudolabels_mol_emb_subsample_fp_concat_dense,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_fp_con...,0.774682,0.563914
nn_retraining_with_pseudolabels_mol_emb_subsample_lpm_trainable,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_lpm_tr...,0.775558,0.561934
nn_retraining_with_pseudolabels_mol_emb_subsample_fp_fixed,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_fp_fixed,0.776084,0.564898
nn_retraining_with_pseudolabels_mol_emb_subsample_fp_trainable,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_fp_tra...,0.779042,0.566706
nn_retraining_with_pseudolabels_mol_emb_subsample_lpm_concat_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_lpm_co...,0.779162,0.559085
nn_retraining_with_pseudolabels_mol_emb_subsample_none,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_none,0.781401,0.558080
nn_retraining_with_pseudolabels_mol_emb_subsample_lpm_fixed,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_lpm_fixed,0.784512,0.562927

### Control methods

In [11]:
df_control_err.sort_values(by="mean_rowwise_rmse")

,dataset_id,method_id,mean_rowwise_rmse,mean_rowwise_mae
ground_truth,neurips-2023-data,ground_truth,0.000000,0.000000
mean_across_celltypes,neurips-2023-data,mean_across_celltypes,0.892474,0.643716
mean_outcome,neurips-2023-data,mean_outcome,0.899233,0.635633
zeros,neurips-2023-data,zeros,0.917925,0.635087
mean_across_compounds,neurips-2023-data,mean_across_compounds,0.942813,0.697865
sample,neurips-2023-data,sample,1.363488,0.963245

## Mean rowwise correlation

### Methods

* `nn_retraining_with_pseudolabels_mol_emb_subsample_lpm_trainable` - small molecule unfreezed embedding was initialized with LPM embedding information and then projected with a Dense layer to match original `emb_out` dimentions.
* `nn_retraining_with_pseudolabels_mol_emb_subsample_fp_trainable` - small molecule unfreezed embedding was initialized with ECFP:2 embedding information and then projected with a Dense layer to match original `emb_out` dimentions.
* `nn_retraining_with_pseudolabels_mol_emb_subsample_none` - Original architecture of models without additional embedding information.
* `nn_retraining_with_pseudolabels_mol_emb_subsample_lpm_concat_dense` - concatenation of fixed LPM embedding with 2 trainable specified in the initial architecture of the models: cell type and small molecule embeddings, before concatenation LPM embedding was projected with an additional Dense layer.
* `nn_retraining_with_pseudolabels_mol_emb_subsample_fp_fixed` - small molecule freezed embedding was initialized with ECFP:2 embedding information and then projected with a Dense layer to match original `emb_out` dimentions.
* `nn_retraining_with_pseudolabels_mol_emb_subsample_lpm_concat_not_dense` - concatenation of fixed LPM embedding with 2 trainable: cell type and small molecule embeddings, before concatenation **no** additional Dense layer was applied.
* `nn_retraining_with_pseudolabels_mol_emb_subsample_fp_concat_dense` - concatenation of fixed ECFP:2 embedding with 2 trainable: cell type and small molecule embeddings, before concatenation ECFP:2 embedding was projected with an additional Dense layer.
* `nn_retraining_with_pseudolabels_mol_emb_subsample_lpm_fixed` - small molecule freezed embedding was initialized with LPM embedding information and then projected with a Dense layer to match original `emb_out` dimentions.
* `nn_retraining_with_pseudolabels_mol_emb_subsample_fp_concat_not_dense` - concatenation of fixed ECFP:2 embedding with 2 trainable: cell type and small molecule embeddings, before concatenation **no** additional Dense layer was applied.

In [12]:
df_method_corr[df_method_corr.index.str.contains('_mol_emb_subsample')].sort_values(by="mean_rowwise_spearman", ascending=False)

,dataset_id,method_id,mean_rowwise_pearson,mean_rowwise_spearman,mean_rowwise_cosine
nn_retraining_with_pseudolabels_mol_emb_subsample_lpm_trainable,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_lpm_tr...,0.494102,0.464417,0.497121
nn_retraining_with_pseudolabels_mol_emb_subsample_fp_trainable,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_fp_tra...,0.492118,0.461952,0.495091
nn_retraining_with_pseudolabels_mol_emb_subsample_none,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_none,0.489683,0.461513,0.492978
nn_retraining_with_pseudolabels_mol_emb_subsample_lpm_concat_dense,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_lpm_co...,0.489070,0.460424,0.492119
nn_retraining_with_pseudolabels_mol_emb_subsample_fp_fixed,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_fp_fixed,0.487055,0.458353,0.490202
nn_retraining_with_pseudolabels_mol_emb_subsample_lpm_concat_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_lpm_co...,0.485886,0.457995,0.489124
nn_retraining_with_pseudolabels_mol_emb_subsample_fp_concat_dense,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_fp_con...,0.484798,0.455403,0.487839
nn_retraining_with_pseudolabels_mol_emb_subsample_lpm_fixed,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_lpm_fixed,0.482364,0.454432,0.485559
nn_retraining_with_pseudolabels_mol_emb_subsample_fp_concat_not_dense,neurips-2023-data,nn_retraining_with_pseudolabels_mol_emb_fp_con...,0.480939,0.453072,0.484098

### Control methods

In [13]:
df_control_corr.sort_values(by="mean_rowwise_spearman", ascending=False)

,dataset_id,method_id,mean_rowwise_pearson,mean_rowwise_spearman,mean_rowwise_cosine
ground_truth,neurips-2023-data,ground_truth,NaN,1.000000,NaN
mean_across_celltypes,neurips-2023-data,mean_across_celltypes,0.297152,0.280571,0.301747
mean_across_compounds,neurips-2023-data,mean_across_compounds,0.259385,0.242509,0.262827
mean_outcome,neurips-2023-data,mean_outcome,0.219819,0.211683,0.226435
sample,neurips-2023-data,sample,0.050696,0.054819,0.053091
zeros,neurips-2023-data,zeros,0.000000,0.000000,0.000000